env:
  global:
  - GCP_PROJECT_ID=pgr301-devops-exam-monster
  - tf_version=0.13.4
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: BryUv1B8OYD+ibBOpZoCSdytKldiY/nNUsZgGOeSP9hP1nUy2byuzUMSPnDg/6WDn3zyHxK0kakVxzI+ElNduE/PzbfTEhGGluX41CbJJ9OmGWullFfe2GDJzfb0Zfi1t7a4j7gSBJ8t7DBr/dznRLx8Lm/lI580wIkXbpoXf5oYTY63JxyREoSSzRFStZaPDqw1SXUHSAunyqGBCdO9ksZE2NYlYSsYMclUUwuZk2xuVXorBZPKQjRZk33xAQiPU/Oeu3a5NpQYvhDwB9aVTB1ZCew0bFNpSmDYqZPTNU3QIs6co84I4FQDKyTSlnRBcxlGW8GLGdOOJXZThy9cW894cek8NqNJUfwZ3seGk35hLEpM713JMA8LC1DPvWUJMfB6DTEBZaXhR7yENYMM5Yompc8xf767aA5AXL8a7bypjpy+5d8ZAwHBle1j+WeJJkaJRyY5smOcSIDKDF9XY77roEujML+qO6+wLGboynP/mnLf/WA91Dz4tYr7LS4Gyl5GelebdznDSyqs7i0fv6bzAaXScz3TNEwhl3FjszeBnC7P+8DO1VTFFHHv9OBF8I3eqf5PAoNzxtcw7/MZJASwDwGQsvpL7uryo9iLkAhz6nTznJ9Qr3q5EqLANx5PNTM/kKlkyTjJbAFyYPfwEZvK8KnWkW6YNdrcAxd++cQ=
  - secure: ATxJG+QlRPyMz6Lvf/txLiNJQCNX20YMshD0TzrgRFWjGaPMStUDFi9JT2VIK/t9udo080fqUSo59PtGmX7ne//9uTYhq0a05QL9riWF3SsXY9HPOsP5gafSiXhMJVBAZ0KfMTAssokXxhUU3BD20c/5Q1z2xgy8o+9lQH3PdAW3n8JyJESQPP2Ct9FNS+C20MqfYJejEgmf2qiR7dxdtanEdYId0iexnKclmw4mygdmYp2jdfiDI8OhMNcEMcDJGYPoDlhQzh/ws39020DSb/G7NdNbwMhZf0jLB2MliU02+jxscRd5SRYnfa5QFUu6FFtEzOta+yPAOg37klmbaVDWSky+Q6kUuTQU3gYAhSuHMC40ZQzFmL+pRZBoO0NGVz845ov5QeSNEoIwx0/uh8CB5LUs5mCQBRF5A6PHbWy4Otq8Ojd+Aule/qRKVTwARc5tnuRWAOKHNAWAjUs4ClfNTh6V1cshIG2Cdp8zthlYBi5EPcTFZ/B+LpcVXQVq6vS3iGceS7yXSbukInTE3xD3G0NYuwOTV+eHBuHLBC9TJ0yuhS0B4n0GnVSshy1BjmGZOOkZkx+zi3fSALYxN6nJHqNUAkd9h+Wfu5m5+CIFKPFOXRUaok0skada83lH30BBJ6EaEvd17ltw21sLhkqH8E8o80DvUG/Wp0AO7BE=
  - secure: FhMCwjO6hRy0IgvnU+Ke+A9fDPZlp6iEEvoWPcVbzCqNMyOWOn/11Hh5oq46SeLqOt8F0Mh1y7l3xb/GVM8OsZ0HZwCUJCxoOow1pxZRHeBCXNsYjM/JAvAg+usN6MmIKNT4Jk2SZZR6k7wZnlZEW8liUuCmVJhR5ofc+bK4h6cMpdU20VKUeMIuw6ppfK3dYJNxBZkfHjPW0X9OVjJ9xFkT8r+zjmuJpWk3s2u5e9cmsH67aD083s1F1ATPozCZlFYWkDQ/U/JuPbYMpXQ7+1+lGMn6ezJA3QZ9bSrrEr0kuqE+WM1p714Xg88oZe2xZHGjXhwkovGVOsuzJgD/wIF1+wB6BUrluIU2C0Tgs6f46sNLhGlqf0CdT2SC4heMHlC4Fyn+CUGxjxOufWkKMwKNMVWTse/KfzhT9zeG+8eVKq9LhzDxXHtHs6dt5+arb4Xf6mOTKVVNnuAWAukFAcfCgOqXP3r0iXmwFqf5ojswNrKNtSKIsxbpNzRVNUUW6iqU3Njlqkkniiu3y73DxqikvYGpp2nirfb9U2voUmgVIkoS5BSJEp367EDiZGw9PlJbTbA5lUbHywuGdgThHvWfGRnBXH0JeMBxxMS2J6iCBXqypF+y1YHL+VYKzCIc8oplhrA63ybyIyNDH06yrIyatRkqLxenS/wM1QgWEo8=
#  - secure: 0dHarixl8ij5/qJ7W8rDnz2MBx56z/BBSuJLYdDX36XM0N4i3NrcN/jM5zS81uLelAgLJiEmOosYRDldkwg7Ea3J3bxS4aYe6Eo8O6s9DV0sXbjA0ESZRCd8YgaktDOYH1EdAGy1vhNtxfCNb9j+SXLMg3vMuCY3OwGMs6TJPAhV3SLJvNw0Il9wYpTO2xcj8krK7mDYlXZTJ+7YzrnKE8rqJU4KvVn240HRimN84kXTd8vNdiR9Jm+mhGX8KL7/0fjdrLztIvpiB7C2iBjO0KpSrBaWsyUhyguX3VH6QBcrSo8ysnHEnJV+Iwp+DNYnExsHrvssRJTKBn6MuOQ6SDqLpdH6YHE2WKEarT0bJtRTZfGwNLlGNOGRVsnTZ5urTQV1x57iF8YZ9dM66ec00EYV4zUcBwJUaU4QXHSibYi54oG8CP7Qob5II278WD9ekOJ66GbP8HoLINMvsQtaWdCMbwp4Rfkt03/UU/QqSfRjgQZgcT5B0PaAZ9ArfzJ1WIfmBU6fTNRmbKVysvQkkXqhoKNgiH+1p9FhNYOVpMamqONzUlQbPNBEKXFq/3aAT9yFd4xMDyfz6UKt6eKLxho88Uvu551xfBF42B/VZzvSjZ7MkXuH5J+qHVRtrv6pDrU+krpYu0bexDFsp4lmGp2/a96d5LUeasJVV5kAO2Q=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
